---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -uat

namespace: flask-uat

resources:
- Namespace.yaml
- ImageStream.yaml
- BuildConfig.yaml
- DeploymentConfig.yaml
- Route.yaml
- Service.yaml
- resourcequota.yaml
- configmap.yaml

commonLabels:
  app: flask

