---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-flask
spec:
  hard:
    pods: "10"

    requests.cpu: "500m"
    requests.memory: "512Mi"

    limits.cpu: "800m"
    limits.memory: "1024Mi"

    configmaps: "10"
    replicationcontrollers: "20"
    secrets: "10"
    services: "5"
    services.loadbalancers: "2"

    persistentvolumeclaims: "10"
    requests.storage: "10Gi"

    requests.ephemeral-storage: 2Gi
    limits.ephemeral-storage: 4Gi 
  
    gp2-csi.storageclass.storage.k8s.io/requests.storage: "8Gi" 
    gp2-csi.storageclass.storage.k8s.io/persistentvolumeclaims: "5" 
    
    gp3-csi.storageclass.storage.k8s.io/requests.storage: "1Gi" 
    gp3-csi.storageclass.storage.k8s.io/persistentvolumeclaims: "1" 
    
    